package it.unisa.model.Filters;

public enum Gen14 {
	ASUS_PRIME_Z790_P,
	ASUS_ProArt_Z790_CREATOR_WIFI,
	ASUS_ROG_MAXIMUS_Z790_HERO,
	MSI_MPG_Z790_EDGE_TI_MAX_WIFI,
	MSI_Z790_GAMING_PLUS_WIFI,
	GIGABYTE_Z790_AORUS_ELITE_AX
}
